### ISSUE TITLE
Can create multiple brownbags for the same Friday, assigned to the same user.

### ISSUE THREAD

**Issue by waiyaki** [AndelaOSP/shufflebox-backend#23]
### Description
- When I POST to `api/shuffle` with `type = 'brownbag'`multiple times, the API creates a new brownbag for the upcoming Friday, regardless of whether one exists for that same Friday or not.
- If the randomizer returns a user who already has a brownbag created for that same Friday, another brownbag is created for the same user, nonetheless.

**Comment by gitgik** [comment]
This has been fixed by PR #27
